// Shape of the AI-generated insight cards in data/insights.json.
// That file is machine-generated by scripts/generate-insights.ts — never hand-edit.

export interface InsightCard {
  matchId: string;
  headline: string;
  body: string;
  /** Each team's probability of winning this match, by team name. */
  probabilities: Record<string, number>;
  /** Each team's title chance at generation time — the next run compares against this. */
  titleChances: Record<string, number>;
  generatedAt: string;
}
